import type { Metadata } from "next";
import "./globals.css";
import "@/app/signin/styles.scss";
import Menu from "@/components/common/side-bar/side_bar";
import { ThemeProvider } from "@/providers/theme-provider";
import ThemeSwitcher from "@/components/common/theme-switcher/theme-switcher";


export const metadata: Metadata = {
  title: "clube bosch",
  description: "Generated by João Pedro and Iago Souza",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ThemeSwitcher />
          {/* <Menu /> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
